apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: www.ticket-app-sz.website
    http:
      paths:
        path: /api/payments/?(.*)
        backend:
          service:
            name: {{ template "ticket-chart.fullname" . }}payments-srv
            port:
              number: 3000
        path: /api/users/?(.*)
        backend:
          service:
            name: {{ template "ticket-chart.fullname" . }}auth-srv
            port:
              number: 3000
        path: /api/tickets/?(.*)
        backend:
          service:
            name: {{ template "ticket-chart.fullname" . }}tickets-srv
            port:
              number: 3000
        path: /api/orders/?(.*)
        backend:
          service:
            name: {{ template "ticket-chart.fullname" . }}orders-srv
            port:
              number: 3000
        path: /?(.*)
        backend:
          service:
            name: {{ template "ticket-chart.fullname" . }}client-srv
            port:
              number: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
#     service.beta.kubernetes.io/do-loadbalancer-hostname: 'www.ticket-app-sz.website'
#   labels:
#     helm.sh/chart: ingress-nginx-2.0.3
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/instance: ingress-nginx
#     app.kubernetes.io/version: 0.32.0
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/component: controller
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# spec:
#   type: LoadBalancer
#   externalTrafficPolicy: Local
#   ports:
#     - name: http
#       port: 80
#       protocol: TCP
#       targetPort: http
#     - name: https
#       port: 443
#       protocol: TCP
#       targetPort: https
#   selector:
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/instance: ingress-nginx
#     app.kubernetes.io/component: controller
